"""BIU DS17 - Python Project 1 - Weather Forecast.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dZGTjDvS3OyltVyd89ekrZQg5uNrzOYS
"""

import os.path
import json

def loadFromJson(path,op):
  try:
    with open(path, 'r') as file:
        deserializedJson = json.load(file)
        file.close()
        return deserializedJson
  except:
    print("the operation did not succeed, please check if the path is correct or the file is open.")

def is_file_exists(filePath):
    if (os.path.exists(filePath)):
        return True

    if (not os.path.exists(filePath)):
        return False

def appendToJson(dic, filePath):
    dumpToJson(dic, filePath, 'a')

def writeToJson(dic, filePath):
    dumpToJson(dic, filePath, 'w')
def dumpToJson(dic, path, op):


    try:
        match op:
            case 'w':
                with open(path, 'w', encoding ='utf8') as file:
                    json.dump(dic, file)
                file.close()


            case 'a':
                with open(path, 'a', encoding ='utf8') as file:
                    json.dump(dic, file)
                file.close()


            case _:
                return print("please provide operation letter, use r = read , w = write or a = append.")

    except:
        print("the operation did not succeed, please check if the path is correct or the file is open.")

def dumpToFile(dic, filePath):
    dumpToJson(dic, filePath, 'w')