"""BIU DS17 - Python Project 1 - Weather Forecast.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dZGTjDvS3OyltVyd89ekrZQg5uNrzOYS
"""

import os
import Weather
import Time
import Json_Handle
import Preferences
import Menus

def main():
    while(not os.path.exists('defaultCity.json')):
        defaultCity = Preferences.setDefaultCity()
        if (defaultCity == None):
            print("You didnt choose a defualt location, please choose a defualt location.")
        if(defaultCity != None):
            print(f"The chosen city is:{defaultCity}")
            break

    print("Hello, Please choose the name of the city that you want to display weather:")
    city = input("City name:")

    if(city == ""):
        try:
            default = Json_Handle.loadFromJson('defaultCity.json', 'r')
            print(f"Since no city was chosen , the information will be provided of the {default}")
            locationZone = Weather.get_weather(default)
            Time.get_local_time()
            Time.timeInzone(locationZone)
        except:
            print("No default location has been found set.")
    else:
        locationZone = Weather.get_weather(city)
        Time.get_local_time()
        Time.timeInzone(locationZone)

    Menus.mainMenu()
main()