"""BIU DS17 - Python Project 1 - Weather Forecast.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dZGTjDvS3OyltVyd89ekrZQg5uNrzOYS
"""

import datetime
import pytz
import Json_Handle

def get_local_time():
    localDateTime = datetime.datetime.now()
    print("Local Time:", localDateTime)
    return localDateTime

def get_local_time_friendly():
    dateTimeYear = datetime.datetime.now().strftime("%Y")
    dateTimeMonth = datetime.datetime.now().strftime("%m")
    dateTimeDay = datetime.datetime.now().strftime("%d")
    dateTimeHour = datetime.datetime.now().strftime("%H")
    dateTimeMinute = datetime.datetime.now().strftime("%M")
    dateTimeSecond = datetime.datetime.now().strftime("%S")
    localDateTime = datetime.datetime.now()
    print("Year:", dateTimeYear, "Month:", dateTimeMonth, "Day:", dateTimeDay, "Hour:", dateTimeHour, "Minute:", dateTimeMinute, "Second:", dateTimeSecond)


def timeInzone(city):
  zone = getZone(city)
  timeZone = pytz.timezone(zone)
  location = datetime.datetime.now(timeZone)
  print("Location Time:", location)

def generateTimeZoneDic(city):
    if(not Json_Handle.is_file_exists('timezones.json')):
        timeZoneDic = {}

        for tz in pytz.all_timezones:
            for letter in tz:
                slash_index = tz.find('/')

                if slash_index != -1:
                    next_word = tz[slash_index + 1:]
                    timeZoneDic[next_word] = tz

        Json_Handle.dumpToFile(timeZoneDic, 'timezones.json')
    else:
        getZone(city)

def getZone(city):
    data = Json_Handle.loadFromJson('timezones.json', 'r')
    for key, value in data.items():
        if(city == key):
            return value

